Swift 5
elegion/ios-Swissors pull request #17
Opened 2019-07-28 11:22 UTC by ildar-gilfanov

2019-07-29 15:20 UTC, chebur commented on Source/Date+Swissors.swift
> +    static func == (dateLeft: Date, dateRight: Date) -> Bool {
метод == есть в свифт 5, может стоит его выпилить?

2019-07-29 15:37 UTC, nesterenkodm requested changes

2019-07-29 15:37 UTC, chebur commented on Source/Dictionary+Swissors.swift
> +    func dictionaryByAddingValues(from dictionary: [Key: Value]) -> [Key: Value] {
есть дефолтный метод `Dictionary.merging`, он делает тоже самое

2019-07-29 15:37 UTC, chebur commented on Source/Dictionary+Swissors.swift
> +    mutating func addValues(from dictionary: [Key: Value]) {
есть дефолтный метод Dictionary.merge, он делает тоже самое

2019-08-05 14:16 UTC, ildar-gilfanov commented on Source/Date+Swissors.swift
> +    static func == (dateLeft: Date, dateRight: Date) -> Bool {
убрал

2019-08-05 14:17 UTC, ildar-gilfanov commented on Source/Dictionary+Swissors.swift
> +    func dictionaryByAddingValues(from dictionary: [Key: Value]) -> [Key: Value] {
убрал

2019-08-05 14:17 UTC, ildar-gilfanov commented on Source/Dictionary+Swissors.swift
> +    mutating func addValues(from dictionary: [Key: Value]) {
убрал

2019-08-05 14:27 UTC, nesterenkodm approved these changes

2019-08-07 09:07 UTC, Kuler29 approved these changes

2019-08-07 09:07 UTC, merged