Swift 3 +  some new methods
elegion/ios-Swissors pull request #4
Opened 2016-12-14 14:07 UTC by Aranoledur

2016-12-14 14:08 UTC, chebur commented
конфликты надо решить

2016-12-14 14:36 UTC, nesterenkodm requested changes

2016-12-14 14:36 UTC, chebur commented on Source/Bundle+Swissors.swift
> +    public func sw_infoDictionaryString(for key: String) -> String? {
почему бы не типизировать параметр? `sw_infoDictionaryValue<T>(for key: String) -> T?`

2016-12-14 14:36 UTC, chebur commented on Source/UIViewController+Swissors.swift
> +    func autoAddSubViewController(_ subViewController: UIViewController, constraintsSetupClosure: @escaping (_ superView: UIView, _ subView: UIView) -> [NSLayoutConstraint]) {
бесмысленный метод, делает тоже самое что и первый

2016-12-14 14:36 UTC, chebur commented on Source/UIWindow+Swissors.swift
> +    public func changeRootViewControllerTo(_ viewController: UIViewController, withTransitionStyle transitionStyle: UIViewAnimationOptions = .transitionCrossDissolve, duration: TimeInterval = CATrans
нужно перетащить этот метод из elnutils, ветка swift

2016-12-14 14:36 UTC, chebur commented on Source/Date+Swissors.swift
> +    public func isEqual(to date: Date) -> Bool {
заменить на `static ==()`

2016-12-14 14:36 UTC, chebur commented on Source/Date+Swissors.swift
> +    public func numberOfUnits(until date: Date, calendarUnit: Calendar.Component, inTimeZone timeZone: TimeZone? = nil) -> Int {
переименовать в `number(of unit: Calendar.Component until date: Date, calendar: Calendar)`

2016-12-14 16:07 UTC, Aranoledur commented on Source/Date+Swissors.swift
> +    public func isEqual(to date: Date) -> Bool {
done

2016-12-14 16:08 UTC, Aranoledur commented on Source/Date+Swissors.swift
> +    public func numberOfUnits(until date: Date, calendarUnit: Calendar.Component, inTimeZone timeZone: TimeZone? = nil) -> Int {
done

2016-12-14 16:40 UTC, Aranoledur commented on Source/Bundle+Swissors.swift
> +    public func sw_infoDictionaryString(for key: String) -> String? {
done

2016-12-14 16:41 UTC, Aranoledur commented on Source/UIViewController+Swissors.swift
> +    func autoAddSubViewController(_ subViewController: UIViewController, constraintsSetupClosure: @escaping (_ superView: UIView, _ subView: UIView) -> [NSLayoutConstraint]) {
done

2016-12-14 16:44 UTC, Aranoledur commented on Source/UIWindow+Swissors.swift
> +    public func changeRootViewControllerTo(_ viewController: UIViewController, withTransitionStyle transitionStyle: UIViewAnimationOptions = .transitionCrossDissolve, duration: TimeInterval = CATrans
done

2016-12-19 12:36 UTC, nesterenkodm commented on Source/Bundle+Swissors.swift
> +    public func sw_infoDictionaryString(for key: String) -> String? {
заменить на `sw_infoDictionaryValue<T>(for key: String) -> T?`

2016-12-19 12:36 UTC, nesterenkodm commented on Source/Bundle+Swissors.swift
> +    public func sw_infoDictionaryBool(for key: String, defaultValue: Bool = false) -> Bool {
удалить, так как этот случай покрывается методом `sw_infoDictionaryValue<T>`

2016-12-19 12:36 UTC, nesterenkodm commented on Source/UIApplication+Swissors.swift
> +    public func sw_presentViewController(_ viewController: UIViewController, inNewWindowWithLevel windowLevel: UIWindowLevel, animated: Bool = true, setupHandler: ((UIWindow) -> Void)? = nil) {
перенести этот метод из ELNUtils ветка swift

2016-12-19 12:36 UTC, nesterenkodm commented on Source/UIViewController+Swissors.swift
> +    public func autoAddSubViewController(_ subViewController: UIViewController, constraintsSetupClosure: @escaping (_ superView: UIView, _ subView: UIView) -> [NSLayoutConstraint]) {
этот метод дублирует предыдущий. удалить

2016-12-19 12:37 UTC, merged